# Site settings
title: Kelly's Portfolio
email: f/xqazqlbp
url: https://github.com/jeromelachaud/freelancer-theme
description: "Kelly Xu's Portfolio"
keywords: "Kelly, Kelly Xu, Portfolio, Designer, Strategic Product Design, Strategic Product Designer"
skills: "A Strategic Way Forward"
meta_author: Xu Kelly

# fonts
font_size_small: '16px'

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
#Donker Blauw 206cb7 "32,108,183" 
#Licht Blauw 8fbfe5
#Licht Blauw grijs d2e2f1 "210,226,241" 
#Donker Donker Blauw 243257
color:
  primary: 206cb7 #About, Header en knopjes licht blauw
  primary-rgb: "32,108,183" #About, Header en Knopjes RGB values licht blauw
  secondary: 243257 #Navbar, Titles donker donker blauw
  secondary-dark: 206cb7 #Footer, Navbar Squares licht blauw

# Footer settings
footer:
  #copyright: Dr. Henry Jekyll
  #location: Location
  social: CV & More
  #credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: google-drive
    url: https://drive.google.com/drive/folders/1A2wCSvAm_ZAo_J-Tva-wCy4AaTSlvfjM?usp=sharing
    description: CV
  - title: linkedin
    url: https://www.linkedin.com/in/kelly-xu-designer/
    description: LinkedIn
  - title: envelope
    url: kellyxukelly@gmail.com
    description: Email
  - title: file
    url: https://rdcu.be/dr55w
    description: Paper

# Postal address (add as many lines as necessary)
#address:
  #- line: 3481 Melrose Place
  #- line: Beverly Hills, CA 90210

# Credits content
#credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
